DROP TABLE IF EXISTS Services;

CREATE TABLE Services (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(100) NOT NULL,
    FileName VARCHAR(100) DEFAULT NULL,
    Description VARCHAR(1000) NOT NULL,
    Features VARCHAR(1000) NOT NULL,
    PricingPlans JSON
);
