DROP TABLE IF EXISTS Schedules;

CREATE TABLE Schedules (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    ContactName VARCHAR(60) NOT NULL,
    SelectedDate DATE NOT NULL,
    Services VARCHAR(500) NOT NULL,
    Timeslots VARCHAR(500) NOT NULL,
    Note VARCHAR(500) DEFAULT NULL,
    Uid VARCHAR(100) DEFAULT NULL
);
